name: docker-evaluation

services:
  docker-evaluation:
    build:
      context: .
      dockerfile: Dockerfile
    image: docker-evaluation:dev
    container_name: docker-evaluation-dev
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    security_opt:
      - no-new-privileges:true
    env_file:
      - .env
