name: docker-evaluation

services:
  docker-evaluation:
    build:
      context: ..
      dockerfile: tests/Dockerfile
    image: docker-evaluation:dev
    container_name: docker-evaluation-dev
    restart: unless-stopped
    ports:
      - "8654:8000"
    volumes:
      - ..:/app
    env_file:
      - ../.env
